################################################################################################
#    _____  _                    _  _       _    _          _____  _                           #
#   / ____|(_)                  | |(_)     | |  (_)        / ____|| |                          #
#  | (___   _  _ __ ___   _ __  | | _  ___ | |_  _   ___  | (___  | |__    ___   _ __   ___    #
#   \___ \ | || '_ ` _ \ | '_ \ | || |/ __|| __|| | / __|  \___ \ | '_ \  / _ \ | '_ \ / __|   #
#   ____) || || | | | | || |_) || || |\__ \| |_ | || (__   ____) || | | || (_) || |_) |\__ \   #
#  |_____/ |_||_| |_| |_|| .__/ |_||_||___/ \__||_| \___| |_____/ |_| |_| \___/ | .__/ |___/   #
#                        | |                                                    | |            #
#                        |_|                                                    |_|            #
#                                                                                              #
################################################################################################
# Sounds: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html                       #
# Materials: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html                 #
################################################################################################
ConfigVersion: 1.0

SellSettings:
  Menu:
    title: "&6&l$ Sell your Items $"
    rows: 5
  Sounds:
    sellSound: ENTITY_ARROW_HIT_PLAYER
    menuCloseSound: UI_TOAST_OUT

BuySettings:
  Sounds:
    menuOpenSound: ENTITY_ARROW_HIT_PLAYER
    menuSaleCompleteSound: ENTITY_PLAYER_LEVELUP
    menuSaleFailedSound: ENTITY_ENDERMAN_TELEPORT